#\uC350
50000 = oxide-copper|minedusty-oxidecopper-icon
#\uC351
50001 = chlorophyte|minedusty-chlorophyte-icon
#\uC352
50002 = aquamerium|minedusty-aquamerium-icon
#\uC353
50003 = carbonicwaste|minedusty-carbonicwaste-icon
#\uC354
50004 = carbonicconcentrator|minedusty-carbonic-concentrator-icon
#\uC355
50005 = carbonicpress|minedusty-carbonic-press-icon
#\uC356
50006 = silicaforge|minedusty-silica-forge-icon
#\uC357
50007 = salt-water|minedusty-salt-water-icon
#\uC358
50008 = solar-panel|minedusty-solar-panel-icon
#\uC359
50009 = powerpylon|minedusty-power-pylon-icon
#\uC35A
50010 = powerpylonwater|minedusty-power-pylon-water-icon
#\uC35B
50011 = crystalbore|minedusty-crystal-bore-icon
#\uC35C
50012 = salinator|minedusty-salinator-icon
#\uC35D
50013 = saltbattery|minedusty-salt-battery-icon
#\uC35E
50014 = biosludgechamber|minedusty-biosludge-chamber-icon
#\uC35F
50015 = electricfurnace|minedusty-electric-furnace-icon
#\uC360
50016 = solidfurnace|minedusty-solid-furnace-icon
#\uC361
50017 = silicadust|minedusty-silicadust-icon
#\uC362
50018 = frostwall|minedusty-frost-wall-icon
#\uC363
50019 = salt|minedusty-salt-icon